import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const production = process.argv[2] === "production";

const banner =
  "/*\n" +
  "THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n" +
  "if you want to view the source, please visit the github repository\n" +
  "*/";

const wasmPlugin = {
  name: "wasm-binary",
  setup(build) {
    build.onResolve({ filter: /sql-wasm\.wasm$/ }, (args) => {
      return {
        path: path.resolve("node_modules", "sql.js", "dist", "sql-wasm.wasm"),
        namespace: "wasm-binary"
      };
    });

    build.onLoad({ filter: /.*/, namespace: "wasm-binary" }, async (args) => {
      const content = await fs.promises.readFile(args.path);
      const base64 = content.toString("base64");
      return {
        contents: `module.exports = ${JSON.stringify(base64)};`,
        loader: "js"
      };
    });
  }
};

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((moduleName) => `node:${moduleName}`)
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  plugins: [wasmPlugin]
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
